# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size_chart',
            name='Gender',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
