# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_auto_20170704_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size_chart',
            name='Gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
