# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0006_image_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_chart',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
