# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_auto_20170704_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size_Chart',
        ),
    ]
